version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/dockerfile.dev
    ports:
      - "5000:5000"
    command: npm run start:dev
  
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run dev
