version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestApp

  backend:
    build:
      context: ./
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
      - "5555:5555"
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - nestApp
  
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - nestApp


volumes:
  postgres_data:

networks:
  nestApp:
    driver: bridge
